// <auto-generated />
namespace ChatServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201902260702025_User-Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
